version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - npm pkg delete scripts.prepare
      - yarn install --frozen-lockfile

  build:
    commands:
      - yarn build
